// module.exports = {
//   /* config options here */
//   webpack: (config, options) => {
//     //This is a must-have in order to prevent a parsing error generated by the zmq
//     // in the saw-tooth sdk
//     // for reason states here:
//     // https://github.com/zeromq/zeromq.js/issues/150
//     // I cant use the the saw-tooth sdk with react,
//     // override for that would be to use a backend server that will
//     // serve as a proxy to the sawtooth app
//     // it is referred as a backend, but it's just a proxy layer
//     if (config.node.target === 'node') config.node.__dirname = false;
//     config.module.rules.push({
//       test: /\.node$/,
//       loader: 'node-loader',
//     });
//     return config;
//   },
// };
